### ISSUE TITLE
你好，请问一下按照流程在ubuntu16.04下run出错，这个是什么情况

### ISSUE THREAD

**Issue by liupengstyle** [yuboona/punctuation-restoration-pytorch#1]
File "train.py", line 335, in <module>
    main(args)
  File "train.py", line 270, in main
    avg_loss, avg_acc = run_one_epoch(tr_data_loader, model, criterion, optimizer, epoch, args)
  File "train.py", line 151, in run_one_epoch
    scores = model(inputs)
  File "/home/liupeng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'hidden'

**Comment by yuboona** [comment]
你好，你用的应该是`./run.sh`运行的。这个调用的是`train.py`训练的，还有另一个`python punctuator.py`的训练方式，里面调用的是`train_use_conf.py`。我后期对训练做了一些修改，这些修改在`train.py`里面没有，所以你可以选择两种解决方案：

1. 使用`python punctuator.py -tr`那条指令去训练
2. 把train.py的代码稍微修改一下，如下所示，修改成和`train_use_conf.py`里面差不多的：

```python
# train.py

    start = time.time()
    for i, (inputs, labels) in enumerate(data_loader):
        # 1. mini_batch data******************************************************
        inputs = Variable(inputs, requires_grad=False)
        labels = Variable(labels, requires_grad=False)

        # 2. forward and compute loss**********************************************
        optimizer.zero_grad()
        # forward compute, use *model()* call the forward()
        scores = model(inputs)
```
修改为
```python
# train_use_conf.py

    hidden = model.init_hidden(args.batch_size)
    # print("hidden_size:", hidden[0].size())
    start = time.time()
    for i, (inputs, labels) in enumerate(data_loader):
        # 1. mini_batch data******************************************************
        inputs = Variable(inputs, requires_grad=False)
        labels = Variable(labels, requires_grad=False)

        # 2. forward and compute loss**********************************************
        optimizer.zero_grad()
        # forward compute, use *model()* call the forward()
        print('', hidden[0].size())
        scores, hidden = model(inputs, hidden, train=True)
```

- 主要区别就是，我加了一个不同batch间的一个hidden状态的传递

**Comment by liupengstyle** [comment]
好的，非常谢谢您，还有一个问题请教一下，您使用的训练数据集是在data10里面，推断数据在data8里面，这个您是怎么指定的呢，从哪里可以看得出来

**Comment by yuboona** [comment]
@liupengstyle 
- 训练：如果你使用的是`.sh`运行的，那训练数据集的指定是在`.sh`文件里的; 如果使用的是`punctuator.py`，那训练数据集的指定，是通过import一个config文件导入的
```python
# punctuator.py
# cinfig文件再conf文件夹下
from conf import TRAINCONF10 as args
from conf import INFERCONF10_seg_4punc as infer_args
```
- 推理：都是用的`punctuator.py`，数据集指定如上（注意使用punctuator进行推理的时候，要保证推理用的模型和训练的模型保持一致）

**Comment by liupengstyle** [comment]
File "punctuator.py", line 22, in <module>
    train.main(args)
  File "/home/liupeng/nlp/biaodian—2/punctuation-restoration-pytorch-master/train/train_use_conf.py", line 209, in main
    avg_loss, avg_acc, avg_acc_2 = run_one_epoch(tr_data_loader, model, criterion,                                         optimizer, epoch, args)
  File "/home/liupeng/nlp/biaodian—2/punctuation-restoration-pytorch-master/train/train_use_conf.py", line 68, in run_one_epoch
    loss = criterion(scores, labels.view(-1))
  File "/home/liupeng/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/liupeng/.local/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/liupeng/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/liupeng/.local/lib/python3.6/site-packages/torch/nn/functional.py", line 1790, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: weight tensor should be defined either for all 6 classes or no classes but got weight tensor of shape: [5] at /pytorch/aten/src/THNN/generic/ClassNLLCriterion.c:29
你好，当用data5这种分字的数据训练时，出现这种报错，这个该怎么处理呢，谢谢哈

**Comment by liupengstyle** [comment]
你好，请教一下，原始数据是怎么处理成训练格式的数据，非目标的标点符号要怎么处理？

**Comment by yuboona** [comment]
@liupengstyle 你好，你可以看一下我的另一个项目[people_paper_2018-2019](https://github.com/yuboona/people_paper_2018-2019)——这个项目里面的`TextProc.ipynb`是用来处理数据中的不需要的标点符号，并获得训练格式的数据的。
