### ISSUE TITLE
No such file or directory: './exp/PRnet10/final10.pth.tar'

### ISSUE THREAD

**Issue by guofengming11** [yuboona/punctuation-restoration-pytorch#2]
直接运行punctuator.py报错No such file or directory: './exp/PRnet10/final10.pth.tar'
![impicture_20210109_164432](https://user-images.githubusercontent.com/67827587/104087335-0955ef00-529a-11eb-90a2-2d095fa85862.jpg)

**Comment by yuboona** [comment]
@guofengming11 你好，在windows上进行训练是`python punctuator.py -tr > ./log/yourLOgName &`
你可能是`-t`参数，触发了进行test的推理测试脚本。推理时，代码会根据`conf.py` 文件中的参数`./exp/PRnet10/final10.pth.tar`，去load已经训练好的模型文件，后续你可以根据自己的需要去更改`conf.py`以改变这一模型的存储和load的路径。

**Comment by guofengming11** [comment]
额 请问这个项目里是不包含预训练模型的是么？我想跑个demo看看效果，是需要先自己训练？

**Comment by guofengming11** [comment]
> @guofengming11 你好，在windows上进行训练是`python punctuator.py -tr > ./log/yourLOgName &`
> 你可能是`-t`参数，触发了进行test的推理测试脚本。推理时，代码会根据`conf.py` 文件中的参数`./exp/PRnet10/final10.pth.tar`，去load已经训练好的模型文件，后续你可以根据自己的需要去更改`conf.py`以改变这一模型的存储和load的路径。

额 请问这个项目里是不包含预训练模型的是么？我想跑个demo看看效果，是需要先自己训练？

**Comment by yuboona** [comment]
@guofengming11 exp没有上传，这个训练挺快的，cpu训练应该也不会超过半个小时。

**Comment by guofengming11** [comment]
好的 谢谢了 星星以点

**Comment by guofengming11** [comment]
好的 谢谢了 星星已点亮

**Comment by yuboona** [comment]
@guofengming11 有其他问题也欢迎发起issue
