### ISSUE TITLE
训练模型和inference模型不一致？

### ISSUE THREAD

**Issue by guofengming11** [yuboona/punctuation-restoration-pytorch#3]
训练过程一切正常生成了模型文件，进行inference加载模型文件的时候报错了，请问这是什么原因呢？

![image](https://user-images.githubusercontent.com/67827587/104124340-582f8180-538b-11eb-93a2-121603ad6f7e.png)

**Comment by yuboona** [comment]
@guofengming11 inference里面有一些bug，等一下会提交新的一版，修正这些错误

**Comment by guofengming11** [comment]
好的 感谢分享

**Comment by yuboona** [comment]
@guofengming11 新版本代码已经提交，可以`git pull`命令更新一下。感谢提问，代码确实有一些小bug没有注意到！
